"""Export generated specialist output to Word (.docx).

Templates are **not** merged via placeholder fields. The active template’s outline and excerpts
are fed to the LLM during drafting; this module writes the model’s ``full_markdown`` / structured
fields into a new document.
"""

from __future__ import annotations

from pathlib import Path

from docx import Document

from app.schemas import SOWSectionsModel


def merge_docx(
    template_path: Path,
    flat_context: dict[str, str],
    output_path: Path,
) -> tuple[bool, str]:
    """
    Build a .docx from specialist ``flat_context``. ``template_path`` is only used to name the
    reference file in the preamble (audit / human context)—we do not inject fields into that binary.

    Returns (False, message) for backward compatibility with callers that expected a (used_template_engine, note) pair.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fname = template_path.name if template_path else "template.docx"
    preamble = (
        f"Draft produced by the specialist pipeline using «{fname}» as structural and boilerplate "
        "reference (headings and excerpts from that file were included in the model context). "
        "This file is not generated by mapping Word merge placeholders; it is the model’s recreated document."
    )
    standalone_docx_from_flat(flat_context, output_path, preamble=preamble)
    return False, "Exported specialist draft to Word (outline-guided; no placeholder merge)."


def merge_or_standalone_docx(
    template_path: Path,
    template_filename: str,
    flat_context: dict[str, str],
    output_path: Path,
) -> str:
    """
    If the workspace template is .docx, merge/render into that file; otherwise build a new .docx
    guided by PDF/XLSX template (same rules as HTTP merge/export).
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    suffix = Path(template_filename).suffix.lower()
    if suffix == ".docx":
        _, note = merge_docx(template_path, flat_context, output_path)
        return note
    preamble = (
        "Reference template file type: PDF or Excel. The system extracted headings, text, or table "
        "previews for the drafting specialists. This Word file contains the generated Statement of Work "
        "content in structured sections—it does not recreate the original file’s exact layout, forms, or print styling."
    )
    return standalone_docx_from_flat(flat_context, output_path, preamble=preamble)


def standalone_docx_from_flat(
    flat_context: dict[str, str],
    output_path: Path,
    *,
    preamble: str | None = None,
) -> str:
    """
    Word document from specialist output. If ``full_markdown`` is present, it is the primary body
    (avoids duplicating the same text in structured fields). Otherwise uses SOW-shaped fields.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc = Document()
    if preamble and preamble.strip():
        doc.add_paragraph(preamble.strip())
    doc.add_paragraph()
    body = (flat_context.get("full_markdown") or "").strip()
    if body:
        doc.add_heading("Specialist draft", level=1)
        for line in body.splitlines():
            doc.add_paragraph(line)
    else:
        doc.add_heading("Generated content", level=1)
        order = [
            ("Purpose", flat_context.get("purpose", "")),
            ("Background", flat_context.get("background", "")),
            ("Scope", flat_context.get("scope", "")),
            ("Deliverables", flat_context.get("deliverables", "")),
            ("Period of Performance", flat_context.get("period_of_performance", "")),
            ("Roles and Responsibilities", flat_context.get("roles_and_responsibilities", "")),
            ("Acceptance Criteria", flat_context.get("acceptance_criteria", "")),
            ("Assumptions and Constraints", flat_context.get("assumptions_and_constraints", "")),
        ]
        for title, block in order:
            if block and str(block).strip():
                doc.add_heading(title, level=2)
                for line in str(block).splitlines():
                    doc.add_paragraph(line)

    doc.save(str(output_path))
    return "Created Word document from specialist output (no placeholder merge)."


def merge_docx_bytes(template_path: Path, flat_context: dict[str, str]) -> tuple[bytes, str]:
    import tempfile

    with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as tmp:
        out_path = Path(tmp.name)
    try:
        _, msg = merge_docx(template_path, flat_context, out_path)
        return out_path.read_bytes(), msg
    finally:
        out_path.unlink(missing_ok=True)


def sow_sections_to_markdown(s: SOWSectionsModel) -> str:
    """Produce a Markdown string from structured sections (prefers ``full_markdown``)."""

    fm = (s.full_markdown or "").strip()
    if fm:
        return fm

    parts: list[str] = []
    order = [
        ("Purpose", "purpose"),
        ("Background", "background"),
        ("Scope", "scope"),
        ("Deliverables", "deliverables"),
        ("Period of Performance", "period_of_performance"),
        ("Roles and Responsibilities", "roles_and_responsibilities"),
        ("Acceptance Criteria", "acceptance_criteria"),
        ("Assumptions and Constraints", "assumptions_and_constraints"),
    ]
    data = s.model_dump()
    for title, key in order:
        block = (data.get(key) or "").strip()
        if block:
            parts.append(f"## {title}\n\n{block}\n")
    out = "\n".join(parts).strip()
    if out:
        return out
    return "[No generated narrative text was available yet.]"


def sow_model_to_flat(s: SOWSectionsModel) -> dict[str, str]:
    return {
        "purpose": s.purpose or "",
        "background": s.background or "",
        "scope": s.scope or "",
        "deliverables": s.deliverables or "",
        "period_of_performance": s.period_of_performance or "",
        "roles_and_responsibilities": s.roles_and_responsibilities or "",
        "acceptance_criteria": s.acceptance_criteria or "",
        "assumptions_and_constraints": s.assumptions_and_constraints or "",
        "full_markdown": s.full_markdown or "",
    }
