FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json /app/
RUN npm ci

COPY . /app
ARG VITE_API_BASE=http://127.0.0.1:8000
ENV VITE_API_BASE=${VITE_API_BASE}
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
